name = "augment-token-manager"
compatibility_date = "2023-12-01"

# Cloudflare Pages 配置
pages_build_output_dir = "public"

# 环境变量配置
[vars]
# ACCESS_PWD 将在 Cloudflare Dashboard 中设置

# KV 存储配置
[[kv_namespaces]]
binding = "TOKENS"
id = "替换为您的生产环境KV命名空间ID"
preview_id = "替换为您的预览环境KV命名空间ID"
